development:
  adapter: redis
  url: <%= ENV.fetch("CABLE_REDIS", "redis://redis:6379/1") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("CABLE_REDIS", "redis://redis:6379/1") %>
  channel_prefix: rails_base_production
